name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/.ssh/usedmarket
          git pull origin main
          ./gradlew build
          pkill -f 'usedmarket-0.0.1-SNAPSHOT.jar' || true
          nohup java -jar build/libs/usedmarket-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

